version: "3.8"

services:
  nginx:
    image: "nginx:stable-alpine"
    restart: unless-stopped
    ports:
      - "8080:80"
    volumes:
      - ./docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - ./:/var/www/aec-test-project
    depends_on:
      - app
    networks:
      - app-network
  app:
    ports:
      - "9999:9000"
    restart: unless-stopped
    build:
      context: docker/app
      dockerfile: Dockerfile
    volumes:
      - ./:/var/www/aec-test-project
    networks:
      - app-network

networks:
  app-network:
